// Bundle scripts/analyze-entry.js and everything it imports into macros/analyze.js: a single file that
// can be pasted into a Foundry Script macro or the console.   Run: npm run build:macro
//
// The bundle is the one build artifact that ships to users, so it is built with as little as possible
// (docs/PLAN.md D11): TypeScript (one package, no dependencies, no native binary) turns each ES module
// into a CommonJS function, and the thirty lines below put those functions into one registry. Nothing
// from node_modules can end up in the output: only relative imports inside scripts/ are followed, and
// anything else fails the build. test/macro-bundle.test.js checks that the committed bundle is current
// and that it behaves exactly like the modules it was built from.
import ts from "typescript";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname, join, posix } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const ENTRY = "scripts/analyze-entry.js";
export const OUTPUT = "macros/analyze.js";
const BANNER = "// GENERATED by dev/build-macro.mjs from scripts/ — do not edit. Paste into a Foundry Script macro and execute.\n" +
  "// Afterwards `d20Analyze({ days: 30, whisper: true })` is available in the console.\n";

/** @returns {{ text: string, modules: string[] }} */
export function buildMacro() {
  /** @type {Map<string, string>} module id (repo-relative path) → CommonJS function body */
  const modules = new Map();
  const add = (id) => {
    if (modules.has(id)) return;
    if (!id.startsWith("scripts/") || !existsSync(join(ROOT, id))) throw new Error(`build-macro: ${id} is not a module under scripts/`);
    const { outputText, diagnostics } = ts.transpileModule(readFileSync(join(ROOT, id), "utf8"), {
      fileName: id,
      reportDiagnostics: true,
      compilerOptions: { allowJs: true, module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, removeComments: true, newLine: ts.NewLineKind.LineFeed },
    });
    if (diagnostics?.length) throw new Error(`build-macro: ${id}: ${ts.flattenDiagnosticMessageText(diagnostics[0].messageText, " ")}`);
    const deps = [];
    const body = outputText.replace(/\brequire\("([^"]+)"\)/g, (_all, spec) => {
      if (!spec.startsWith(".")) throw new Error(`build-macro: ${id} imports "${spec}"; only relative imports inside scripts/ can be bundled`);
      const dep = posix.normalize(posix.join(posix.dirname(id), spec));
      deps.push(dep);
      return `require(${JSON.stringify(dep)})`;
    });
    modules.set(id, body);
    for (const dep of deps) add(dep);
  };
  add(ENTRY);

  const defs = [...modules].map(([id, body]) => `${JSON.stringify(id)}: function (require, module, exports) {\n${body.trimEnd()}\n}`).join(",\n");
  const text = `${BANNER}(() => {
const defs = {
${defs}
};
const cache = {};
const load = (id) => {
  if (!Object.hasOwn(defs, id)) throw new Error("d20 analyzer: unknown module " + id);
  if (!cache[id]) { cache[id] = { exports: {} }; defs[id](load, cache[id], cache[id].exports); }
  return cache[id].exports;
};
load(${JSON.stringify(ENTRY)});
})();
`;
  const parsed = ts.createSourceFile(OUTPUT, text, ts.ScriptTarget.ES2022, false, ts.ScriptKind.JS);
  if (parsed.parseDiagnostics?.length) throw new Error(`build-macro: the bundle does not parse: ${ts.flattenDiagnosticMessageText(parsed.parseDiagnostics[0].messageText, " ")}`);
  return { text, modules: [...modules.keys()] };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { text, modules } = buildMacro();
  writeFileSync(join(ROOT, OUTPUT), text);
  console.log(`${OUTPUT}  ${(text.length / 1024).toFixed(1)}kb  from ${modules.length} modules (TypeScript ${ts.version})`);
}
