// Bundle the pure layer + scripts/analyze-entry.js into macros/analyze.js (single file, pasteable
// into a Foundry Script macro or the console). Run: npm run build:macro
import { build } from "esbuild";

const result = await build({
  entryPoints: ["scripts/analyze-entry.js"],
  bundle: true,
  format: "iife",
  target: "es2022",
  outfile: "macros/analyze.js",
  legalComments: "none",
  banner: { js: "// GENERATED by dev/build-macro.mjs from scripts/ — do not edit. Paste into a Foundry Script macro and execute.\n// Afterwards `d20Analyze({ days: 30, whisper: true })` is available in the console." },
  logLevel: "info",
});
if (result.errors.length) process.exit(1);
