// GENERATED by dev/build-macro.mjs from scripts/ — do not edit. Paste into a Foundry Script macro and execute.
// Afterwards `d20Analyze({ days: 30, whisper: true })` is available in the console.
(() => {
  var __defProp = Object.defineProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };

  // scripts/capture/extractors/pf2e-check.js
  var pf2e_check_exports = {};
  __export(pf2e_check_exports, {
    extract: () => extract,
    id: () => id,
    keptNewRoll: () => keptNewRoll,
    matches: () => matches,
    on: () => on
  });

  // scripts/constants.js
  var MODULE_ID = "pf2e-d20-session-tracker";
  var D20 = Object.freeze({
    faces: 20,
    mean: 10.5,
    variance: 33.25,
    sd: Math.sqrt(33.25)
  });
  var PF2E_CHECK_TYPES = Object.freeze([
    "attack-roll",
    "check",
    "counteract-check",
    "flat-check",
    "initiative",
    "perception-check",
    "saving-throw",
    "skill-check"
  ]);

  // scripts/capture/dice-walk.js
  function parseRoll(entry) {
    if (entry && typeof entry === "object") return entry;
    if (typeof entry !== "string") return null;
    try {
      return JSON.parse(entry);
    } catch {
      return null;
    }
  }
  function d20sOfRoll(roll, rollIndex = 0) {
    const out = [];
    let termIndex = 0;
    const visitTerm = (term) => {
      if (!term || typeof term !== "object") return;
      if (term.class === "Die" || term.faces !== void 0 && Array.isArray(term.results)) {
        if (Number(term.faces) === 20) {
          const results = Array.isArray(term.results) ? term.results : [];
          const formula = dieFormula(term);
          results.forEach((r, resultIndex) => {
            const natural = Number(r?.result);
            if (!Number.isInteger(natural)) return;
            out.push({ natural, kept: r.active !== false && !r.discarded, formula, rollIndex, termIndex, resultIndex, dieIndex: -1 });
          });
        }
        termIndex++;
        return;
      }
      if (Array.isArray(term.rolls)) for (const inner of term.rolls) visitRoll(inner);
      if (term.roll && typeof term.roll === "object") visitRoll(term.roll);
      if (Array.isArray(term.terms)) for (const t of term.terms) visitTerm(t);
    };
    const visitRoll = (r) => {
      if (!r || typeof r !== "object") return;
      if (Array.isArray(r.terms)) for (const t of r.terms) visitTerm(t);
    };
    visitRoll(roll);
    return out;
  }
  function d20sOfMessage(rolls) {
    const out = [];
    (rolls ?? []).forEach((entry, rollIndex) => {
      const roll = parseRoll(entry);
      if (!roll) return;
      const total = Number.isFinite(Number(roll.total)) ? Number(roll.total) : null;
      for (const d of d20sOfRoll(roll, rollIndex)) {
        out.push({ ...d, dieIndex: out.length, total, rollFormula: typeof roll.formula === "string" ? roll.formula : null });
      }
    });
    return out;
  }
  function dieFormula(term) {
    const number = Number.isInteger(Number(term.number)) ? Number(term.number) : 1;
    const mods = Array.isArray(term.modifiers) ? term.modifiers.join("") : "";
    return `${number}d${term.faces}${mods}`;
  }

  // scripts/capture/reroll-html.js
  var DISCARD_OPEN = /<div\s+class="[^"]*\breroll-discard\b[^"]*"[^>]*>/i;
  var DIE_LI = /<li\s+class="[^"]*\broll\b[^"]*\bdie\b[^"]*\bd20\b[^"]*"[^>]*>\s*(\d{1,2})\s*<\/li>/gi;
  var DICE_TOTAL = /<(?:span|div|h4)\s+class="[^"]*\bdice-total\b[^"]*"[^>]*>\s*(-?\d+)\s*<\/(?:span|div|h4)>/i;
  function parseRerollDiscard(html) {
    if (typeof html !== "string" || !html) return { naturals: [], total: null, found: false };
    const open = DISCARD_OPEN.exec(html);
    if (!open) return { naturals: [], total: null, found: false };
    const start = open.index + open[0].length;
    const block = html.slice(start, findDivEnd(html, start));
    const naturals = [];
    for (const m of block.matchAll(DIE_LI)) naturals.push(Number(m[1]));
    const totalMatch = DICE_TOTAL.exec(block);
    return { naturals, total: totalMatch ? Number(totalMatch[1]) : null, found: true };
  }
  function findDivEnd(html, from) {
    const tag = /<\/?div\b[^>]*>/gi;
    tag.lastIndex = from;
    let depth = 1;
    let m;
    while (m = tag.exec(html)) {
      if (m[0][1] === "/") {
        depth--;
        if (depth === 0) return m.index;
      } else depth++;
    }
    return html.length;
  }

  // scripts/capture/extractors/pf2e-check.js
  var id = "pf2e-check";
  var on = ["create", "backfill"];
  function matches(msg) {
    const type = msg.flags?.pf2e?.context?.type;
    return typeof type === "string" && PF2E_CHECK_TYPES.includes(type);
  }
  function extract(msg, ctx, base) {
    const context = msg.flags?.pf2e?.context ?? {};
    const dice = d20sOfMessage(msg.rolls);
    if (!dice.length) return [];
    const common = {
      type: context.type,
      source: "pf2e-check",
      domains: Array.isArray(context.domains) ? [...context.domains] : [],
      ident: context.identifier ?? null,
      action: context.action ?? null,
      dc: numberOrNull(context.dc?.value),
      dcVisible: typeof context.dc?.visible === "boolean" ? context.dc.visible : null,
      outcome: context.outcome ?? null,
      unadjustedOutcome: context.unadjustedOutcome ?? null,
      isReroll: context.isReroll === true,
      rollTwice: typeof context.rollTwice === "string" ? context.rollTwice : null,
      mode: context.messageMode ?? context.rollMode ?? null
    };
    const records = dice.map((d) => base({
      ...common,
      id: `${msg._id}:r${d.rollIndex}:t${d.termIndex}:d${d.resultIndex}`,
      dieIndex: d.dieIndex,
      natural: d.natural,
      kept: d.kept,
      formula: d.formula,
      total: d.total
    }));
    if (common.isReroll) return withRerollDice(msg, records, common, base);
    return records;
  }
  function withRerollDice(msg, records, common, base) {
    const e = msg.flags?.[MODULE_ID]?.reroll;
    const shown = records[0];
    if (e && Array.isArray(e.newNaturals) && Array.isArray(e.oldNaturals) && e.oldMessageId) {
      const keptNew = keptNewRoll(e.keep, e.oldTotal, e.newTotal);
      const out = [];
      out.push(base({
        ...common,
        ...pick(shown, ["formula", "dieIndex"]),
        id: `${msg._id}:r0:t0:d0`,
        natural: e.newNaturals[0] ?? shown?.natural ?? null,
        kept: keptNew,
        total: keptNew ? shown?.total ?? null : numberOrNull(e.newTotal),
        isReroll: true,
        rerollOf: e.oldMessageId,
        resource: e.resource ?? void 0,
        source: "reroll-enrich"
      }));
      out.push(base({
        ...common,
        ...pick(shown, ["formula"]),
        id: `${e.oldMessageId}:r0:t0:d0`,
        msgId: e.oldMessageId,
        dieIndex: 0,
        natural: e.oldNaturals[0] ?? null,
        kept: !keptNew,
        total: keptNew ? numberOrNull(e.oldTotal) : shown?.total ?? null,
        ts: msg.timestamp - 1,
        isReroll: false,
        rerolledBy: msg._id,
        rerollOutcome: keptNew ? "discarded" : "kept",
        resource: e.resource ?? void 0,
        source: "reroll-enrich"
      }));
      for (let i = 1; i < e.newNaturals.length; i++) {
        out.push(base({ ...common, formula: shown?.formula ?? "2d20", id: `${msg._id}:r0:t0:d${i}`, dieIndex: i, natural: e.newNaturals[i], kept: false, total: null, isReroll: true, rerollOf: e.oldMessageId, source: "reroll-enrich" }));
      }
      for (let i = 1; i < e.oldNaturals.length; i++) {
        out.push(base({ ...common, formula: shown?.formula ?? "2d20", id: `${e.oldMessageId}:r0:t0:d${i}`, msgId: e.oldMessageId, dieIndex: i, natural: e.oldNaturals[i], kept: false, total: null, ts: msg.timestamp - 1, isReroll: false, rerolledBy: msg._id, source: "reroll-enrich" }));
      }
      return out;
    }
    const parsed = parseRerollDiscard(msg.content);
    const discards = parsed.naturals.length ? parsed.naturals : [null];
    const extra = discards.map((natural, i) => base({
      ...common,
      formula: shown?.formula ?? "1d20",
      id: `${msg._id}:html:${i}`,
      dieIndex: records.length + i,
      natural,
      kept: false,
      total: parsed.total,
      isReroll: true,
      source: "reroll-html",
      ...natural === null ? { discardUnknown: true } : {}
    }));
    return [...records, ...extra];
  }
  function keptNewRoll(keep, oldTotal, newTotal) {
    if (keep === "higher" && Number(oldTotal) > Number(newTotal)) return false;
    if (keep === "lower" && Number(oldTotal) < Number(newTotal)) return false;
    return true;
  }
  function numberOrNull(v) {
    const n = Number(v);
    return v === null || v === void 0 || Number.isNaN(n) ? null : n;
  }
  function pick(obj, keys) {
    const out = {};
    if (!obj) return out;
    for (const k of keys) if (obj[k] !== void 0) out[k] = obj[k];
    return out;
  }

  // scripts/capture/extractors/raw-d20.js
  var raw_d20_exports = {};
  __export(raw_d20_exports, {
    extract: () => extract2,
    id: () => id2,
    matches: () => matches2,
    on: () => on2
  });
  var id2 = "raw-d20";
  var on2 = ["create", "backfill"];
  function matches2(msg) {
    const type = msg.flags?.pf2e?.context?.type;
    if (typeof type === "string") return false;
    return d20sOfMessage(msg.rolls).length > 0;
  }
  function extract2(msg, ctx, base) {
    if (ctx.captureRawRolls === false) return [];
    const type = msg.flags?.core?.initiativeRoll ? "initiative" : "raw";
    return d20sOfMessage(msg.rolls).map((d) => base({
      id: `${msg._id}:r${d.rollIndex}:t${d.termIndex}:d${d.resultIndex}`,
      dieIndex: d.dieIndex,
      natural: d.natural,
      kept: d.kept,
      formula: d.formula,
      total: d.total,
      type,
      source: "raw"
    }));
  }

  // scripts/capture/extractors/toolbelt-saves.js
  var toolbelt_saves_exports = {};
  __export(toolbelt_saves_exports, {
    extract: () => extract3,
    id: () => id3,
    matches: () => matches3,
    on: () => on3
  });
  var id3 = "toolbelt-saves";
  var on3 = ["create", "update", "backfill"];
  var FLAG_SCOPE = "pf2e-toolbelt";
  function matches3(msg) {
    const saves = savesOf(msg);
    return !!saves && Object.keys(saves).length > 0;
  }
  function extract3(msg, ctx, base) {
    const saves = savesOf(msg) ?? {};
    const helper = msg.flags?.[FLAG_SCOPE]?.targetHelper ?? {};
    const targets = indexTargets(helper);
    const saveSlug = helper.save?.statistic ?? helper.save?.slug ?? helper.saveStatistic ?? null;
    const dc = numberOrNull2(helper.save?.dc ?? helper.dc);
    const out = [];
    for (const [targetKey, save] of Object.entries(saves)) {
      if (!save || typeof save !== "object") continue;
      const natural = numberOrNull2(save.die ?? save.natural ?? firstD20(save.roll));
      const total = numberOrNull2(save.value ?? save.total ?? save.roll?.total);
      const outcome = normalizeOutcome(save.success ?? save.outcome ?? save.degree);
      const target = targets[targetKey] ?? {};
      const baseId = `${msg._id}:tb:${targetKey}`;
      const prev = ctx.existing?.(baseId);
      const seq = prev && prev.natural !== natural ? seqOf(prev.id) + 1 : seqOf(prev?.id ?? `${baseId}:0`);
      out.push(base({
        id: `${baseId}:${seq}`,
        dieIndex: out.length,
        natural,
        kept: true,
        formula: "1d20",
        total,
        type: "saving-throw",
        source: "toolbelt",
        domains: saveSlug ? [saveSlug, "saving-throw"] : ["saving-throw"],
        ident: saveSlug,
        dc,
        dcVisible: dc !== null ? true : null,
        outcome,
        isReroll: save.rerolled === true || seq > 0,
        actorId: target.actor ?? save.actor ?? null,
        tokenId: target.token ?? targetKey,
        alias: target.name ?? null,
        userId: ctx.event === "update" && ctx.updaterUserId ? ctx.updaterUserId : save.user ?? save.userId ?? null,
        userGuess: !(ctx.event === "update" && ctx.updaterUserId) && !(save.user ?? save.userId)
      }));
    }
    return out;
  }
  function savesOf(msg) {
    const helper = msg.flags?.[FLAG_SCOPE]?.targetHelper;
    if (!helper || typeof helper !== "object") return null;
    const saves = helper.saves;
    return saves && typeof saves === "object" ? saves : null;
  }
  function indexTargets(helper) {
    const out = {};
    const list = Array.isArray(helper.targets) ? helper.targets : [];
    for (const t of list) {
      if (typeof t === "string") {
        const id5 = t.split(".").pop();
        out[id5] = { token: id5 };
        continue;
      }
      if (t && typeof t === "object") {
        const id5 = t.token ?? t.id ?? t.uuid?.split(".").pop();
        if (id5) out[id5] = { token: id5, actor: t.actor ?? null, name: t.name ?? null };
      }
    }
    return out;
  }
  function firstD20(roll) {
    if (!roll || typeof roll !== "object") return null;
    const terms = Array.isArray(roll.terms) ? roll.terms : [];
    for (const t of terms) if (Number(t?.faces) === 20 && Array.isArray(t.results) && t.results[0]) return t.results[0].result;
    return null;
  }
  function normalizeOutcome(v) {
    if (typeof v === "string") {
      const s = v.replace(/[-_\s]/g, "").toLowerCase();
      if (s === "criticalsuccess") return "criticalSuccess";
      if (s === "criticalfailure") return "criticalFailure";
      if (s === "success" || s === "failure") return s;
    }
    if (typeof v === "number") return ["criticalFailure", "failure", "success", "criticalSuccess"][v] ?? null;
    return null;
  }
  function seqOf(id5) {
    const n = Number(String(id5).split(":").pop());
    return Number.isInteger(n) ? n : 0;
  }
  function numberOrNull2(v) {
    const n = Number(v);
    return v === null || v === void 0 || Number.isNaN(n) ? null : n;
  }

  // scripts/capture/extractors/flat-check.js
  var flat_check_exports = {};
  __export(flat_check_exports, {
    extract: () => extract4,
    id: () => id4,
    matches: () => matches4,
    on: () => on4,
    parseFlatCheckContent: () => parseFlatCheckContent
  });
  var id4 = "flat-check";
  var on4 = ["create", "backfill"];
  var PATTERNS = [
    /<(?:span|div|h4)\s+class="[^"]*\bdice-total\b[^"]*"[^>]*>\s*(\d{1,2})\s*<\//i,
    /<li\s+class="[^"]*\bdie\b[^"]*\bd20\b[^"]*"[^>]*>\s*(\d{1,2})\s*<\/li>/i,
    /data-(?:result|roll|total)="(\d{1,2})"/i,
    /\bclass="[^"]*\b(?:roll-result|flat-check-result|result)\b[^"]*"[^>]*>\s*(\d{1,2})\s*</i
  ];
  var DC_PATTERN = /\bDC\s*:?\s*(\d{1,2})\b/i;
  function matches4(msg) {
    return msg.flags?.["pf2-flat-check"] === true;
  }
  function parseFlatCheckContent(html) {
    if (typeof html !== "string") return { natural: null, dc: null };
    let natural = null;
    for (const re of PATTERNS) {
      const m = re.exec(html);
      if (m) {
        natural = Number(m[1]);
        break;
      }
    }
    const dcm = DC_PATTERN.exec(html);
    return { natural: natural !== null && natural >= 1 && natural <= 20 ? natural : null, dc: dcm ? Number(dcm[1]) : null };
  }
  function extract4(msg, ctx, base) {
    const { natural, dc } = parseFlatCheckContent(msg.content);
    return [base({
      id: `${msg._id}:flat:0`,
      dieIndex: 0,
      natural,
      kept: true,
      formula: "1d20",
      total: natural,
      type: "flat-check",
      source: "pf2-flat-check",
      dc,
      dcVisible: dc !== null ? true : null,
      outcome: natural !== null && dc !== null ? natural >= dc ? "success" : "failure" : null,
      userGuess: true,
      // author is always the GM client; the attacker is only known via the speaker
      ...natural === null ? { valueHidden: true } : {}
    })];
  }

  // scripts/capture/extractors/index.js
  var EXTRACTORS = [pf2e_check_exports, raw_d20_exports, toolbelt_saves_exports, flat_check_exports];

  // scripts/capture/normalize.js
  function messageToRollRecords(msg, ctx) {
    if (!msg || typeof msg !== "object" || !msg._id) return [];
    const ts = Number(msg.timestamp);
    if (!Number.isFinite(ts)) return [];
    const base = makeBase(msg, ctx, ts);
    const out = [];
    for (const ex of EXTRACTORS) {
      if (!ex.on.includes(ctx.event)) continue;
      let hit = false;
      try {
        hit = ex.matches(msg);
      } catch {
        hit = false;
      }
      if (!hit) continue;
      out.push(...ex.extract(msg, ctx, base));
    }
    return out;
  }
  function classifyMessage(msg) {
    for (const ex of EXTRACTORS) {
      try {
        if (ex.matches(msg)) return ex.id;
      } catch {
      }
    }
    if (msg?.flags?.pf2e?.context?.type === "damage-roll") return "damage";
    if (typeof msg?.flags?.pf2e?.context?.type === "string") return "substituted-or-no-d20";
    return null;
  }
  function makeBase(msg, ctx, ts) {
    const sessionKey = ctx.sessionKeyFor(ts);
    const speaker = msg.speaker ?? {};
    const whispered = Array.isArray(msg.whisper) && msg.whisper.length > 0;
    const defaults = {
      msgId: msg._id,
      ts,
      sessionKey,
      userId: typeof msg.author === "string" ? msg.author : msg.author?._id ?? msg.author?.id ?? msg.user ?? null,
      actorId: speaker.actor ?? null,
      tokenId: speaker.token ?? null,
      alias: speaker.alias ?? null,
      natural: null,
      kept: true,
      formula: "1d20",
      total: null,
      type: "raw",
      source: "raw",
      domains: [],
      ident: null,
      action: null,
      dc: null,
      dcVisible: null,
      outcome: null,
      unadjustedOutcome: null,
      isReroll: false,
      rollTwice: null,
      mode: null,
      blind: msg.blind === true,
      whispered,
      inCombat: ctx.inCombat ?? null
    };
    return (overrides) => (
      /** @type {import("../types.js").RollRecord} */
      { ...defaults, ...overrides }
    );
  }

  // scripts/sessions/bucket.js
  var DEFAULT_TIMEZONE = "America/Chicago";
  var DEFAULT_BOUNDARY_HOUR = 6;
  var DAY_MS = 864e5;
  var formatters = /* @__PURE__ */ new Map();
  function formatterFor(timezone) {
    let fmt = formatters.get(timezone);
    if (!fmt) {
      fmt = new Intl.DateTimeFormat("en-US", {
        timeZone: timezone,
        hourCycle: "h23",
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit"
      });
      formatters.set(timezone, fmt);
    }
    return fmt;
  }
  function wallClock(ts, timezone = DEFAULT_TIMEZONE) {
    const out = { year: 0, month: 0, day: 0, hour: 0, minute: 0 };
    for (const part of formatterFor(timezone).formatToParts(ts)) {
      if (part.type in out) out[part.type] = Number(part.value);
    }
    if (out.hour === 24) out.hour = 0;
    return out;
  }
  function sessionKeyFor(ts, { timezone = DEFAULT_TIMEZONE, boundaryHour = DEFAULT_BOUNDARY_HOUR } = {}) {
    const w = wallClock(ts, timezone);
    let dayUtc = Date.UTC(w.year, w.month - 1, w.day);
    if (w.hour < boundaryHour) dayUtc -= DAY_MS;
    return isoDate(dayUtc);
  }
  function sessionLabel(key, locale = "en-US") {
    const [y, m, d] = key.split("-").map(Number);
    const weekday = new Intl.DateTimeFormat(locale, { weekday: "short", timeZone: "UTC" }).format(Date.UTC(y, m - 1, d));
    return `${key} ${weekday}`;
  }
  function compareKeys(a, b) {
    return a < b ? -1 : a > b ? 1 : 0;
  }
  function isoDate(utcMs) {
    return new Date(utcMs).toISOString().slice(0, 10);
  }

  // scripts/stats/normal.js
  function erf(x) {
    if (x === 0) return 0;
    const sign = x < 0 ? -1 : 1;
    const ax = Math.abs(x);
    const t = 1 / (1 + 0.3275911 * ax);
    const poly = t * (0.254829592 + t * (-0.284496736 + t * (1.421413741 + t * (-1.453152027 + t * 1.061405429))));
    return sign * (1 - poly * Math.exp(-ax * ax));
  }
  function normalCdf(z) {
    if (!Number.isFinite(z)) return z > 0 ? 1 : z < 0 ? 0 : NaN;
    return 0.5 * (1 + erf(z / Math.SQRT2));
  }

  // scripts/stats/binomial.js
  function logChoose(n, k) {
    if (k < 0 || k > n) return -Infinity;
    k = Math.min(k, n - k);
    let s = 0;
    for (let i = 1; i <= k; i++) s += Math.log(n - k + i) - Math.log(i);
    return s;
  }
  function binomialPmf(n, k, p) {
    if (k < 0 || k > n || n < 0) return 0;
    if (p <= 0) return k === 0 ? 1 : 0;
    if (p >= 1) return k === n ? 1 : 0;
    return Math.exp(logChoose(n, k) + k * Math.log(p) + (n - k) * Math.log(1 - p));
  }
  function binomialAtLeast(n, k, p) {
    if (k <= 0) return 1;
    if (k > n) return 0;
    let s = 0;
    for (let i = k; i <= n; i++) s += binomialPmf(n, i, p);
    return Math.min(1, s);
  }
  function binomialAtMost(n, k, p) {
    if (k < 0) return 0;
    if (k >= n) return 1;
    let s = 0;
    for (let i = 0; i <= k; i++) s += binomialPmf(n, i, p);
    return Math.min(1, s);
  }

  // scripts/stats/luck.js
  var DEFAULT_GUARDS = Object.freeze({ minN: 5, thinN: 15 });
  function luckSummary(naturals, guards = DEFAULT_GUARDS) {
    const xs = naturals.filter((v) => Number.isInteger(v) && v >= 1 && v <= 20);
    const n = xs.length;
    const minN = guards.minN ?? DEFAULT_GUARDS.minN;
    const thinN = guards.thinN ?? DEFAULT_GUARDS.thinN;
    if (n === 0) {
      return { n: 0, mean: null, delta: null, z: null, percentile: null, zGuard: "none", nat20: faceStats(0, 0), nat1: faceStats(0, 0) };
    }
    const mean = xs.reduce((s, v) => s + v, 0) / n;
    const delta = mean - D20.mean;
    const z = delta / (D20.sd / Math.sqrt(n));
    const zGuard = n < minN ? "none" : n < thinN ? "thin" : "ok";
    return {
      n,
      mean,
      delta,
      z,
      percentile: normalCdf(z),
      zGuard,
      nat20: faceStats(n, xs.filter((v) => v === 20).length),
      nat1: faceStats(n, xs.filter((v) => v === 1).length)
    };
  }
  function faceStats(n, count) {
    const p = 1 / 20;
    return {
      count,
      expected: n * p,
      pAtLeast: n ? binomialAtLeast(n, count, p) : null,
      // excess
      pAtMost: n ? binomialAtMost(n, count, p) : null
      // drought
    };
  }

  // scripts/stats/basic.js
  function histogram(naturals) {
    const h = new Array(20).fill(0);
    for (const v of naturals) if (Number.isInteger(v) && v >= 1 && v <= 20) h[v - 1]++;
    return h;
  }

  // scripts/analyze-entry.js
  var TAG = "d20 tracker";
  async function analyze({
    days = 14,
    timezone = DEFAULT_TIMEZONE,
    boundaryHour = DEFAULT_BOUNDARY_HOUR,
    countMode = "all",
    // "all" physical dice, or "kept" only
    includeRaw = true,
    includeBlind = true,
    groupBy = "user",
    // "user" | "actor"
    whisper = false,
    // post the latest evening's table to the GM as a whisper
    minRolls = 1
    // hide evenings with fewer dice
  } = {}) {
    const since = Date.now() - days * 864e5;
    const messages = game.messages.contents.filter((m) => m.timestamp >= since).map((m) => m.toObject());
    const ctx = { sessionKeyFor: (ts) => sessionKeyFor(ts, { timezone, boundaryHour }), event: "backfill", captureRawRolls: includeRaw };
    const coverage = {};
    const records = [];
    for (const m of messages) {
      const kind = classifyMessage(m) ?? (m.rolls?.length ? "roll-without-d20" : "no-roll");
      coverage[kind] = (coverage[kind] ?? 0) + 1;
      records.push(...messageToRollRecords(m, ctx));
    }
    const counted = records.filter((r) => r.natural !== null && (countMode === "all" || r.kept) && (includeBlind || !(r.blind || r.whispered)));
    const label = (id5) => groupBy === "actor" ? game.actors.get(id5)?.name ?? counted.find((r) => r.actorId === id5)?.alias ?? String(id5) : game.users.get(id5)?.name ?? String(id5);
    const keyOf = (r) => (groupBy === "actor" ? r.actorId : r.userId) ?? "unknown";
    const evenings = {};
    for (const r of counted) (evenings[r.sessionKey] ??= []).push(r);
    const keys = Object.keys(evenings).sort(compareKeys);
    const tables = {};
    for (const key of keys) {
      const recs = evenings[key];
      if (recs.length < minRolls) continue;
      const groups = {};
      for (const r of recs) (groups[keyOf(r)] ??= []).push(r.natural);
      const rows = Object.entries(groups).map(([id5, naturals]) => {
        const s = luckSummary(naturals);
        return {
          who: label(id5),
          n: s.n,
          mean: round(s.mean, 2),
          delta: round(s.delta, 2),
          z: round(s.z, 2),
          pct: s.percentile === null ? null : Math.round(s.percentile * 100),
          nat20: `${s.nat20.count} vs ${s.nat20.expected.toFixed(1)}`,
          nat1: `${s.nat1.count} vs ${s.nat1.expected.toFixed(1)}`,
          guard: s.zGuard,
          hist: histogram(naturals).join(" ")
        };
      }).sort((a, b) => (b.z ?? -99) - (a.z ?? -99));
      const party = luckSummary(recs.map((r) => r.natural));
      tables[key] = { rows, party: { n: party.n, mean: round(party.mean, 2), z: round(party.z, 2), pct: party.percentile === null ? null : Math.round(party.percentile * 100) } };
      console.group(`${TAG} | ${sessionLabel(key)} \u2014 ${recs.length} dice, party mean ${tables[key].party.mean}, party z ${tables[key].party.z}`);
      console.table(rows);
      console.groupEnd();
    }
    console.log(`${TAG} | coverage over ${messages.length} messages in the last ${days} days:`, coverage);
    console.log(`${TAG} | ${records.length} d20 records, ${counted.length} counted (${countMode}); evenings: ${keys.join(", ") || "none"}`);
    console.log(`${TAG} | records by source:`, countBy(records, (r) => r.source), "| by type:", countBy(records, (r) => r.type));
    if (whisper && keys.length) {
      const key = keys[keys.length - 1];
      const t = tables[key];
      const html = `<h3>${TAG}: ${sessionLabel(key)}</h3><p>${t.party.n} dice, party mean ${t.party.mean}, z ${t.party.z}</p><table><tr><th>who</th><th>n</th><th>mean</th><th>z</th><th>nat20</th><th>nat1</th></tr>` + t.rows.map((r) => `<tr><td>${r.who}</td><td>${r.n}</td><td>${r.mean}</td><td>${r.guard === "ok" ? r.z : `(${r.z})`}</td><td>${r.nat20}</td><td>${r.nat1}</td></tr>`).join("") + `</table>`;
      await ChatMessage.create({ content: html, whisper: game.users.filter((u) => u.isGM).map((u) => u.id) });
    }
    return { coverage, tables, records, counted: counted.length };
  }
  function round(v, d) {
    return v === null || v === void 0 || !Number.isFinite(v) ? null : Number(v.toFixed(d));
  }
  function countBy(arr, fn) {
    const o = {};
    for (const x of arr) {
      const k = fn(x);
      o[k] = (o[k] ?? 0) + 1;
    }
    return o;
  }
  globalThis.d20Analyze = analyze;
  analyze();
})();
