// GENERATED by dev/build-macro.mjs from scripts/ — do not edit. Paste into a Foundry Script macro and execute.
// Afterwards `d20Analyze({ days: 30, whisper: true })` is available in the console.
(() => {
const defs = {
"scripts/analyze-entry.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.analyze = analyze;
const normalize_js_1 = require("scripts/capture/normalize.js");
const bucket_js_1 = require("scripts/sessions/bucket.js");
const luck_js_1 = require("scripts/stats/luck.js");
const basic_js_1 = require("scripts/stats/basic.js");
const TAG = "d20 tracker";
async function analyze({ days = 14, timezone = bucket_js_1.DEFAULT_TIMEZONE, boundaryHour = bucket_js_1.DEFAULT_BOUNDARY_HOUR, countMode = "all", includeRaw = true, includeBlind = true, groupBy = "user", whisper = false, minRolls = 1, } = {}) {
    const since = Date.now() - days * 86_400_000;
    const messages = game.messages.contents.filter((m) => m.timestamp >= since).map((m) => m.toObject());
    const ctx = { sessionKeyFor: (ts) => (0, bucket_js_1.sessionKeyFor)(ts, { timezone, boundaryHour }), event: "backfill", captureRawRolls: includeRaw };
    const coverage = Object.create(null);
    const records = [];
    for (const m of messages) {
        const kind = (0, normalize_js_1.classifyMessage)(m) ?? (m.rolls?.length ? "roll-without-d20" : "no-roll");
        coverage[kind] = (coverage[kind] ?? 0) + 1;
        records.push(...(0, normalize_js_1.messageToRollRecords)(m, ctx));
    }
    const counted = records.filter((r) => r.natural !== null && (countMode === "all" || r.kept) && (includeBlind || !(r.blind || r.whispered)));
    const label = (id) => groupBy === "actor"
        ? (game.actors.get(id)?.name ?? counted.find((r) => r.actorId === id)?.alias ?? String(id))
        : (game.users.get(id)?.name ?? String(id));
    const keyOf = (r) => (groupBy === "actor" ? r.actorId : r.userId) ?? "unknown";
    const evenings = Object.create(null);
    for (const r of counted)
        (evenings[r.sessionKey] ??= []).push(r);
    const keys = Object.keys(evenings).sort(bucket_js_1.compareKeys);
    const tables = Object.create(null);
    for (const key of keys) {
        const recs = evenings[key];
        if (recs.length < minRolls)
            continue;
        const groups = Object.create(null);
        for (const r of recs)
            (groups[keyOf(r)] ??= []).push(r.natural);
        const rows = Object.entries(groups).map(([id, naturals]) => {
            const s = (0, luck_js_1.luckSummary)(naturals);
            return {
                who: label(id), n: s.n, mean: round(s.mean, 2), delta: round(s.delta, 2), z: round(s.z, 2),
                pct: s.percentile === null ? null : Math.round(s.percentile * 100),
                nat20: `${s.nat20.count} vs ${s.nat20.expected.toFixed(1)}`, nat1: `${s.nat1.count} vs ${s.nat1.expected.toFixed(1)}`,
                guard: s.zGuard, hist: (0, basic_js_1.histogram)(naturals).join(" "),
            };
        }).sort((a, b) => (b.z ?? -99) - (a.z ?? -99));
        const party = (0, luck_js_1.luckSummary)(recs.map((r) => r.natural));
        tables[key] = { rows, party: { n: party.n, mean: round(party.mean, 2), z: round(party.z, 2), pct: party.percentile === null ? null : Math.round(party.percentile * 100) } };
        console.group(`${TAG} | ${(0, bucket_js_1.sessionLabel)(key)} — ${recs.length} dice, party mean ${tables[key].party.mean}, party z ${tables[key].party.z}`);
        console.table(rows);
        console.groupEnd();
    }
    console.log(`${TAG} | coverage over ${messages.length} messages in the last ${days} days:`, coverage);
    console.log(`${TAG} | ${records.length} d20 records, ${counted.length} counted (${countMode}); evenings: ${keys.join(", ") || "none"}`);
    console.log(`${TAG} | records by source:`, countBy(records, (r) => r.source), "| by type:", countBy(records, (r) => r.type));
    if (whisper && keys.length) {
        const key = keys[keys.length - 1];
        const t = tables[key];
        const html = `<h3>${TAG}: ${esc((0, bucket_js_1.sessionLabel)(key))}</h3><p>${esc(t.party.n)} dice, party mean ${esc(t.party.mean)}, z ${esc(t.party.z)}</p>` +
            `<table><tr><th>who</th><th>n</th><th>mean</th><th>z</th><th>nat20</th><th>nat1</th></tr>` +
            t.rows.map((r) => `<tr><td>${esc(r.who)}</td><td>${esc(r.n)}</td><td>${esc(r.mean)}</td><td>${esc(r.guard === "ok" ? r.z : `(${r.z})`)}</td><td>${esc(r.nat20)}</td><td>${esc(r.nat1)}</td></tr>`).join("") + `</table>`;
        await ChatMessage.create({ content: html, whisper: game.users.filter((u) => u.isGM).map((u) => u.id) });
    }
    return { coverage, tables, records, counted: counted.length };
}
function esc(v) { return String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])); }
function round(v, d) { return v === null || v === undefined || !Number.isFinite(v) ? null : Number(v.toFixed(d)); }
function countBy(arr, fn) { const o = Object.create(null); for (const x of arr) {
    const k = fn(x);
    o[k] = (o[k] ?? 0) + 1;
} return o; }
globalThis.d20Analyze = analyze;
analyze();
},
"scripts/capture/normalize.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.messageToRollRecords = messageToRollRecords;
exports.classifyMessage = classifyMessage;
const index_js_1 = require("scripts/capture/extractors/index.js");
const sanitize_js_1 = require("scripts/capture/sanitize.js");
function messageToRollRecords(msg, ctx) {
    if (!msg || typeof msg !== "object" || typeof msg._id !== "string" || !msg._id || msg._id.length > 64)
        return [];
    const ts = effectiveTimestamp(msg, ctx);
    if (ts === null)
        return [];
    const base = makeBase(msg, ctx, ts);
    const out = [];
    for (const ex of index_js_1.EXTRACTORS) {
        if (!ex.on.includes(ctx.event))
            continue;
        try {
            if (!ex.matches(msg))
                continue;
            for (const r of ex.extract(msg, ctx, base)) {
                const clean = (0, sanitize_js_1.sanitizeRecord)(r);
                if (clean && out.length < sanitize_js_1.MAX_DICE_PER_MESSAGE)
                    out.push(clean);
            }
        }
        catch (e) {
            ctx.warn?.(`extractor ${ex.id} skipped message ${msg._id}`, e);
        }
    }
    return out;
}
function effectiveTimestamp(msg, ctx) {
    const claimed = Number(msg.timestamp);
    if (!Number.isFinite(claimed) || claimed <= 0)
        return null;
    const now = typeof ctx.now === "function" ? Number(ctx.now()) : NaN;
    if (!Number.isFinite(now))
        return claimed;
    const byGM = ctx.isGM?.((0, sanitize_js_1.authorOf)(msg)) === true;
    if (ctx.event === "create" && !byGM && Math.abs(now - claimed) > sanitize_js_1.CLOCK_SKEW_MS)
        return now;
    if (claimed > now + sanitize_js_1.CLOCK_SKEW_MS)
        return now;
    return claimed;
}
function classifyMessage(msg) {
    for (const ex of index_js_1.EXTRACTORS) {
        try {
            if (ex.matches(msg))
                return ex.id;
        }
        catch { }
    }
    if (msg?.flags?.pf2e?.context?.type === "damage-roll")
        return "damage";
    if (typeof msg?.flags?.pf2e?.context?.type === "string")
        return "substituted-or-no-d20";
    return null;
}
function makeBase(msg, ctx, ts) {
    let sessionKey;
    const speaker = msg.speaker ?? {};
    const whispered = Array.isArray(msg.whisper) && msg.whisper.length > 0;
    const defaults = {
        msgId: msg._id,
        ts,
        userId: (0, sanitize_js_1.authorOf)(msg),
        actorId: speaker.actor ?? null,
        tokenId: speaker.token ?? null,
        alias: speaker.alias ?? null,
        natural: null,
        kept: true,
        formula: "1d20",
        total: null,
        type: "raw",
        source: "raw",
        domains: [],
        ident: null,
        action: null,
        dc: null,
        dcVisible: null,
        outcome: null,
        unadjustedOutcome: null,
        isReroll: false,
        rollTwice: null,
        mode: null,
        blind: msg.blind === true,
        whispered,
        inCombat: ctx.inCombat ?? null,
    };
    return (overrides) => {
        sessionKey ??= ctx.sessionKeyFor(ts);
        return ({ ...defaults, sessionKey, ...overrides });
    };
}
},
"scripts/capture/extractors/index.js": function (require, module, exports) {
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.EXTRACTORS = void 0;
const pf2eCheck = __importStar(require("scripts/capture/extractors/pf2e-check.js"));
const rawD20 = __importStar(require("scripts/capture/extractors/raw-d20.js"));
const toolbeltSaves = __importStar(require("scripts/capture/extractors/toolbelt-saves.js"));
const flatCheck = __importStar(require("scripts/capture/extractors/flat-check.js"));
exports.EXTRACTORS = [pf2eCheck, rawD20, toolbeltSaves, flatCheck];
},
"scripts/capture/extractors/pf2e-check.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.on = exports.id = void 0;
exports.matches = matches;
exports.extract = extract;
exports.deriveStat = deriveStat;
exports.keptNewRoll = keptNewRoll;
const constants_js_1 = require("scripts/constants.js");
const dice_walk_js_1 = require("scripts/capture/dice-walk.js");
const reroll_html_js_1 = require("scripts/capture/reroll-html.js");
const sanitize_js_1 = require("scripts/capture/sanitize.js");
exports.id = "pf2e-check";
exports.on = ["create", "backfill"];
function matches(msg) {
    const type = msg.flags?.pf2e?.context?.type;
    return typeof type === "string" && constants_js_1.PF2E_CHECK_TYPES.includes(type) && (0, dice_walk_js_1.d20sOfMessage)(msg.rolls).length > 0;
}
function extract(msg, ctx, base) {
    const context = msg.flags?.pf2e?.context ?? {};
    const dice = (0, dice_walk_js_1.d20sOfMessage)(msg.rolls);
    if (!dice.length)
        return [];
    const domains = Array.isArray(context.domains) ? [...context.domains] : [];
    const common = {
        type: context.type,
        source: "pf2e-check",
        domains,
        stat: deriveStat(context.type, context.identifier ?? null, domains),
        ident: context.identifier ?? null,
        action: context.action ?? null,
        dc: numberOrNull(context.dc?.value),
        dcVisible: typeof context.dc?.visible === "boolean" ? context.dc.visible : null,
        outcome: context.outcome ?? null,
        unadjustedOutcome: context.unadjustedOutcome ?? null,
        isReroll: context.isReroll === true,
        rollTwice: typeof context.rollTwice === "string" ? context.rollTwice : null,
        mode: context.messageMode ?? context.rollMode ?? null,
    };
    const records = dice.map((d) => base({
        ...common,
        id: `${msg._id}:r${d.rollIndex}:t${d.termIndex}:d${d.resultIndex}`,
        dieIndex: d.dieIndex,
        natural: d.natural,
        kept: d.kept,
        formula: d.formula,
        total: d.total,
    }));
    if (common.isReroll)
        return withRerollDice(msg, records, common, ctx, base);
    return records;
}
function withRerollDice(msg, records, common, ctx, base) {
    const shown = records[0];
    const e = readEnrichment(msg, records);
    if (e) {
        const { keptNew, oldMessageId: oldId } = e;
        const out = [];
        out.push(base({
            ...common, ...pick(shown, ["formula", "dieIndex"]),
            id: `${msg._id}:r0:t0:d0`, natural: e.newNaturals[0], kept: keptNew,
            total: keptNew ? shown?.total ?? null : e.newTotal,
            isReroll: true, rerollOf: oldId, resource: e.resource, source: "reroll-enrich",
        }));
        for (let i = 1; i < e.newNaturals.length; i++) {
            out.push(base({ ...common, formula: shown?.formula ?? "2d20", id: `${msg._id}:r0:t0:d${i}`, dieIndex: i, natural: e.newNaturals[i], kept: false, total: null, isReroll: true, rerollOf: oldId, source: "reroll-enrich" }));
        }
        const storedDice = storedDiceOf(ctx, oldId);
        if (!mayTouchOriginal(msg, oldId, storedDice, ctx))
            return out;
        const link = { kept: !keptNew, rerolledBy: msg._id, rerollOutcome: keptNew ? "discarded" : "kept", resource: e.resource };
        if (storedDice.length) {
            const original = storedDice.find((r) => r.rerolledBy === msg._id) ?? storedDice.find((r) => r.kept) ?? storedDice[0];
            out.push({ ...original, ...link });
            return out;
        }
        out.push(base({
            ...common, ...pick(shown, ["formula"]),
            id: `${oldId}:r0:t0:d0`, msgId: oldId, dieIndex: 0,
            natural: e.oldNaturals[0], total: keptNew ? e.oldTotal : shown?.total ?? null,
            ts: shown.ts - 1, isReroll: false, ...link, source: "reroll-enrich",
        }));
        for (let i = 1; i < e.oldNaturals.length; i++) {
            out.push(base({ ...common, formula: shown?.formula ?? "2d20", id: `${oldId}:r0:t0:d${i}`, msgId: oldId, dieIndex: i, natural: e.oldNaturals[i], kept: false, total: null, ts: shown.ts - 1, isReroll: false, rerolledBy: msg._id, source: "reroll-enrich" }));
        }
        return out;
    }
    const parsed = (0, reroll_html_js_1.parseRerollDiscard)(msg.content);
    const discards = parsed.naturals.length ? parsed.naturals : [null];
    const extra = discards.map((natural, i) => base({
        ...common, formula: shown?.formula ?? "1d20",
        id: `${msg._id}:html:${i}`, dieIndex: records.length + i, natural, kept: false, total: parsed.total,
        isReroll: true, source: "reroll-html", ...(natural === null ? { discardUnknown: true } : {}),
    }));
    return [...records, ...extra];
}
const KEEP = ["new", "higher", "lower"];
const byNumber = (a, b) => a - b;
function readEnrichment(msg, records) {
    const e = msg.flags?.[constants_js_1.MODULE_ID]?.reroll;
    if (!e || typeof e !== "object")
        return null;
    if (!(0, sanitize_js_1.isDocumentId)(e.oldMessageId) || e.oldMessageId === msg._id)
        return null;
    const oldNaturals = (0, sanitize_js_1.naturalsOf)(e.oldNaturals), newNaturals = (0, sanitize_js_1.naturalsOf)(e.newNaturals);
    if (!oldNaturals.length || !newNaturals.length)
        return null;
    const oldTotal = numberOrNull(e.oldTotal), newTotal = numberOrNull(e.newTotal);
    const keptNew = keptNewRoll(KEEP.includes(e.keep) ? e.keep : "new", oldTotal, newTotal);
    const shown = records.map((r) => r.natural).sort(byNumber).join();
    if (shown !== [...(keptNew ? newNaturals : oldNaturals)].sort(byNumber).join())
        return null;
    return { oldMessageId: e.oldMessageId, oldNaturals, newNaturals, oldTotal, newTotal, keptNew, resource: typeof e.resource === "string" ? e.resource : undefined };
}
function storedDiceOf(ctx, msgId) {
    if (typeof ctx.find !== "function")
        return [];
    return [0, 1, 2, 3].map((i) => ctx.find(`${msgId}:r0:t0:d${i}`)).filter(Boolean);
}
function mayTouchOriginal(msg, oldId, storedDice, ctx) {
    const author = (0, sanitize_js_1.authorOf)(msg);
    if (ctx.isGM?.(author) === true)
        return true;
    if (storedDice.some((r) => r.userId !== author))
        return false;
    const liveAuthor = ctx.messageAuthor?.(oldId) ?? null;
    return !liveAuthor || liveAuthor === author;
}
const SAVES = ["fortitude", "reflex", "will"];
const SKILLS = ["acrobatics", "arcana", "athletics", "crafting", "deception", "diplomacy", "intimidation", "medicine", "nature", "occultism", "performance", "religion", "society", "stealth", "survival", "thievery"];
function deriveStat(type, identifier, domains) {
    const has = (s) => domains.includes(s);
    if (type === "saving-throw")
        return SAVES.find(has) ?? identifier ?? "save";
    if (type === "perception-check")
        return "perception";
    if (type === "flat-check")
        return "flat-check";
    if (type === "counteract-check")
        return "counteract";
    if (type === "skill-check" || type === "initiative" || type === "check") {
        const skill = SKILLS.find(has) ?? domains.find((d) => /-lore$/.test(d)) ?? null;
        if (skill)
            return skill;
        if (has("perception"))
            return "perception";
        if (identifier && /^[a-z][a-z-]*$/.test(identifier))
            return identifier;
        return type === "initiative" ? "initiative" : null;
    }
    if (type === "attack-roll") {
        if (has("spell-attack-roll"))
            return "spell-attack";
        if (has("ranged-attack-roll"))
            return "ranged-strike";
        if (has("melee-attack-roll"))
            return "melee-strike";
        return "strike";
    }
    return identifier ?? null;
}
function keptNewRoll(keep, oldTotal, newTotal) {
    if (keep === "higher" && Number(oldTotal) > Number(newTotal))
        return false;
    if (keep === "lower" && Number(oldTotal) < Number(newTotal))
        return false;
    return true;
}
function numberOrNull(v) {
    const n = Number(v);
    return v === null || v === undefined || Number.isNaN(n) ? null : n;
}
function pick(obj, keys) {
    const out = {};
    if (!obj)
        return out;
    for (const k of keys)
        if (obj[k] !== undefined)
            out[k] = obj[k];
    return out;
}
},
"scripts/constants.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PF2E_CHECK_TYPES = exports.D20 = exports.SCHEMA_VERSION = exports.MODULE_TITLE = exports.MODULE_ID = void 0;
exports.MODULE_ID = "pf2e-d20-session-tracker";
exports.MODULE_TITLE = "PF2e d20 Session Tracker";
exports.SCHEMA_VERSION = 1;
exports.D20 = Object.freeze({
    faces: 20,
    mean: 10.5,
    variance: 33.25,
    sd: Math.sqrt(33.25),
});
exports.PF2E_CHECK_TYPES = Object.freeze([
    "attack-roll",
    "check",
    "counteract-check",
    "flat-check",
    "initiative",
    "perception-check",
    "saving-throw",
    "skill-check",
]);
},
"scripts/capture/dice-walk.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.parseRoll = parseRoll;
exports.d20sOfRoll = d20sOfRoll;
exports.d20sOfMessage = d20sOfMessage;
exports.messageHasD20 = messageHasD20;
const sanitize_js_1 = require("scripts/capture/sanitize.js");
const MAX_DEPTH = 12;
const MAX_TERMS = 2000;
const MAX_ROLLS = 50;
const MAX_ROLL_JSON = 200_000;
function parseRoll(entry) {
    if (entry && typeof entry === "object")
        return entry;
    if (typeof entry !== "string" || entry.length > MAX_ROLL_JSON)
        return null;
    try {
        const roll = JSON.parse(entry);
        return roll && typeof roll === "object" ? roll : null;
    }
    catch {
        return null;
    }
}
function d20sOfRoll(roll, rollIndex = 0, limit = sanitize_js_1.MAX_DICE_PER_MESSAGE) {
    const out = [];
    let termIndex = 0;
    let budget = MAX_TERMS;
    const visitTerm = (term, depth) => {
        if (!term || typeof term !== "object" || depth > MAX_DEPTH || budget-- <= 0 || out.length >= limit)
            return;
        if (term.class === "Die" || (term.faces !== undefined && Array.isArray(term.results))) {
            if (Number(term.faces) === 20) {
                const results = Array.isArray(term.results) ? term.results : [];
                const formula = dieFormula(term);
                for (let resultIndex = 0; resultIndex < results.length && out.length < limit; resultIndex++) {
                    const r = results[resultIndex];
                    const natural = Number(r?.result);
                    if (!(0, sanitize_js_1.isNatural)(natural))
                        continue;
                    out.push({ natural, kept: r.active !== false && !r.discarded, formula, rollIndex, termIndex, resultIndex, dieIndex: -1 });
                }
            }
            termIndex++;
            return;
        }
        if (Array.isArray(term.rolls))
            for (const inner of term.rolls)
                visitRoll(inner, depth + 1);
        if (term.roll && typeof term.roll === "object")
            visitRoll(term.roll, depth + 1);
        if (Array.isArray(term.terms))
            for (const t of term.terms)
                visitTerm(t, depth + 1);
    };
    const visitRoll = (r, depth) => {
        if (!r || typeof r !== "object" || depth > MAX_DEPTH)
            return;
        if (Array.isArray(r.terms))
            for (const t of r.terms)
                visitTerm(t, depth + 1);
    };
    visitRoll(roll, 0);
    return out;
}
function d20sOfMessage(rolls) {
    const out = [];
    const list = Array.isArray(rolls) ? rolls : [];
    for (let rollIndex = 0; rollIndex < list.length && rollIndex < MAX_ROLLS && out.length < sanitize_js_1.MAX_DICE_PER_MESSAGE; rollIndex++) {
        const roll = parseRoll(list[rollIndex]);
        if (!roll)
            continue;
        const total = Number.isFinite(Number(roll.total)) ? Number(roll.total) : null;
        for (const d of d20sOfRoll(roll, rollIndex, sanitize_js_1.MAX_DICE_PER_MESSAGE - out.length)) {
            out.push({ ...d, dieIndex: out.length, total, rollFormula: typeof roll.formula === "string" ? roll.formula.slice(0, 80) : null });
        }
    }
    return out;
}
function messageHasD20(rolls) {
    return d20sOfMessage(rolls).length > 0;
}
function dieFormula(term) {
    const number = Number.isInteger(Number(term.number)) ? Number(term.number) : 1;
    const mods = Array.isArray(term.modifiers) ? term.modifiers.filter((m) => typeof m === "string").join("") : "";
    return `${number}d20${mods}`.slice(0, 24);
}
},
"scripts/capture/sanitize.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CLOCK_SKEW_MS = exports.MAX_HTML_LENGTH = exports.MAX_DICE_PER_MESSAGE = void 0;
exports.authorOf = authorOf;
exports.isDocumentId = isDocumentId;
exports.isNatural = isNatural;
exports.naturalsOf = naturalsOf;
exports.slugOrNull = slugOrNull;
exports.sanitizeRecord = sanitizeRecord;
exports.MAX_DICE_PER_MESSAGE = 24;
exports.MAX_HTML_LENGTH = 50_000;
exports.CLOCK_SKEW_MS = 15 * 60 * 1000;
const DOCUMENT_ID = /^[A-Za-z0-9]{16}$/;
const SLUG = /^[a-z0-9][a-z0-9-]{0,47}$/;
const TOKEN = /^[A-Za-z0-9][A-Za-z0-9.-]{0,79}$/;
const ROW_KEY = /^[A-Za-z0-9][A-Za-z0-9:_-]{0,159}$/;
const OUTCOMES = ["criticalSuccess", "success", "failure", "criticalFailure"];
const MODES = ["roll", "publicroll", "gmroll", "blindroll", "selfroll"];
const ROLL_TWICE = ["keep-higher", "keep-lower"];
const REROLL_OUTCOMES = ["kept", "discarded"];
function authorOf(msg) {
    return typeof msg?.author === "string" ? msg.author : (msg?.author?._id ?? msg?.author?.id ?? msg?.user ?? null);
}
function isDocumentId(v) {
    return typeof v === "string" && DOCUMENT_ID.test(v);
}
function isNatural(v) {
    return Number.isInteger(v) && v >= 1 && v <= 20;
}
function naturalsOf(v, max = 4) {
    return Array.isArray(v) ? v.slice(0, max).map(Number).filter(isNatural) : [];
}
function slugOrNull(v) {
    return typeof v === "string" && SLUG.test(v) ? v : null;
}
function tokenOrNull(v) {
    return typeof v === "string" && TOKEN.test(v) ? v : null;
}
function text(v, max) {
    if (typeof v !== "string" || !v)
        return null;
    return v.length > max ? v.slice(0, max) : v;
}
function finite(v, limit = 100_000) {
    if (v === null || v === undefined || v === "")
        return null;
    const n = Number(v);
    return Number.isFinite(n) && Math.abs(n) <= limit ? n : null;
}
const oneOf = (v, list) => (typeof v === "string" && list.includes(v) ? v : null);
const idish = (v) => (typeof v === "string" && v.length > 0 && v.length <= 64 ? v : null);
function sanitizeRecord(r) {
    if (!r || typeof r !== "object")
        return null;
    const id = text(r.id, 160), msgId = idish(r.msgId), sessionKey = text(r.sessionKey, 40);
    if (!id || !msgId || !sessionKey || !Number.isFinite(r.ts))
        return null;
    if (msgId.includes(":") || !id.startsWith(`${msgId}:`))
        return null;
    if (!ROW_KEY.test(id))
        return null;
    const natural = r.natural === null || r.natural === undefined ? null : Number(r.natural);
    if (natural !== null && !isNatural(natural))
        return null;
    const out = {
        id, msgId, sessionKey,
        dieIndex: Number.isInteger(r.dieIndex) && r.dieIndex >= 0 ? r.dieIndex : 0,
        ts: r.ts,
        userId: idish(r.userId),
        actorId: idish(r.actorId),
        tokenId: idish(r.tokenId),
        alias: text(r.alias, 80),
        natural,
        kept: r.kept !== false,
        formula: text(r.formula, 24) ?? "1d20",
        total: finite(r.total),
        type: slugOrNull(r.type) ?? "raw",
        source: slugOrNull(r.source) ?? "raw",
        domains: Array.isArray(r.domains) ? r.domains.slice(0, 60).map(tokenOrNull).filter(Boolean) : [],
        stat: slugOrNull(r.stat),
        ident: tokenOrNull(r.ident),
        action: tokenOrNull(r.action),
        dc: finite(r.dc, 1000),
        dcVisible: typeof r.dcVisible === "boolean" ? r.dcVisible : null,
        outcome: oneOf(r.outcome, OUTCOMES),
        unadjustedOutcome: oneOf(r.unadjustedOutcome, OUTCOMES),
        isReroll: r.isReroll === true,
        rollTwice: oneOf(r.rollTwice, ROLL_TWICE),
        mode: oneOf(r.mode, MODES),
        blind: r.blind === true,
        whispered: r.whispered === true,
        inCombat: typeof r.inCombat === "boolean" ? r.inCombat : null,
    };
    if (r.userGuess === true)
        out.userGuess = true;
    const rerollOf = text(r.rerollOf, 160);
    if (rerollOf)
        out.rerollOf = rerollOf;
    if (idish(r.rerolledBy))
        out.rerolledBy = r.rerolledBy;
    if (oneOf(r.rerollOutcome, REROLL_OUTCOMES))
        out.rerollOutcome = r.rerollOutcome;
    if (typeof r.resource === "string" && /^[A-Za-z][A-Za-z0-9-]{0,39}$/.test(r.resource))
        out.resource = r.resource;
    if (r.valueHidden === true)
        out.valueHidden = true;
    if (r.discardUnknown === true)
        out.discardUnknown = true;
    return out;
}
},
"scripts/capture/reroll-html.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.parseRerollDiscard = parseRerollDiscard;
exports.looksLikeReroll = looksLikeReroll;
const html_scan_js_1 = require("scripts/capture/html-scan.js");
const sanitize_js_1 = require("scripts/capture/sanitize.js");
const MAX_DISCARDED_DICE = 4;
function parseRerollDiscard(content) {
    const html = (0, html_scan_js_1.prepareHtml)(content);
    const open = html ? (0, html_scan_js_1.findOpenTag)(html, "div", "reroll-discard") : null;
    if (!open)
        return { naturals: [], total: null, found: false };
    const block = html.slice(open.contentStart, (0, html_scan_js_1.findCloseTag)(html, "div", open.contentStart));
    const isD20 = (e) => e.classes.includes("roll") && e.classes.includes("die") && e.classes.includes("d20");
    const naturals = (0, html_scan_js_1.numericElements)(block, ["li"]).filter((e) => isD20(e) && (0, sanitize_js_1.isNatural)(e.value)).slice(0, MAX_DISCARDED_DICE).map((e) => e.value);
    const total = (0, html_scan_js_1.numericElements)(block, ["span", "div", "h4"]).find((e) => e.classes.includes("dice-total"));
    return { naturals, total: total ? total.value : null, found: true };
}
function looksLikeReroll(html) {
    return typeof html === "string" && /\breroll-(?:discard|second)\b/.test(html);
}
},
"scripts/capture/html-scan.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prepareHtml = prepareHtml;
exports.classesOf = classesOf;
exports.numericElements = numericElements;
exports.findOpenTag = findOpenTag;
exports.findCloseTag = findCloseTag;
const sanitize_js_1 = require("scripts/capture/sanitize.js");
const ATTRS = "[^<>]{0,400}";
function prepareHtml(html) {
    if (typeof html !== "string" || !html)
        return "";
    return (html.length > sanitize_js_1.MAX_HTML_LENGTH ? html.slice(0, sanitize_js_1.MAX_HTML_LENGTH) : html).replace(/\s+/g, " ");
}
function classesOf(attrs) {
    const m = /\bclass ?= ?"([^"<>]{0,300})"/i.exec(attrs ?? "");
    return m ? m[1].split(" ").filter(Boolean) : [];
}
function numericElements(html, tags) {
    const re = new RegExp(`<(${tags.join("|")})\\b(${ATTRS})> ?(-?\\d{1,4}) ?</\\1 ?>`, "gi");
    const out = [];
    for (const m of html.matchAll(re))
        out.push({ tag: m[1].toLowerCase(), classes: classesOf(m[2]), value: Number(m[3]) });
    return out;
}
function findOpenTag(html, tag, className) {
    const re = new RegExp(`<${tag}\\b(${ATTRS})>`, "gi");
    for (const m of html.matchAll(re)) {
        if (classesOf(m[1]).includes(className))
            return { index: m.index ?? 0, contentStart: (m.index ?? 0) + m[0].length };
    }
    return null;
}
function findCloseTag(html, tag, from) {
    const re = new RegExp(`</?${tag}\\b${ATTRS}>`, "gi");
    re.lastIndex = from;
    let depth = 1;
    let m;
    while ((m = re.exec(html))) {
        if (m[0][1] === "/") {
            depth--;
            if (depth === 0)
                return m.index;
        }
        else
            depth++;
    }
    return html.length;
}
},
"scripts/capture/extractors/raw-d20.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.on = exports.id = void 0;
exports.matches = matches;
exports.extract = extract;
const dice_walk_js_1 = require("scripts/capture/dice-walk.js");
exports.id = "raw-d20";
exports.on = ["create", "backfill"];
function matches(msg) {
    const type = msg.flags?.pf2e?.context?.type;
    if (typeof type === "string")
        return false;
    return (0, dice_walk_js_1.d20sOfMessage)(msg.rolls).length > 0;
}
function extract(msg, ctx, base) {
    if (ctx.captureRawRolls === false)
        return [];
    const type = msg.flags?.core?.initiativeRoll ? "initiative" : "raw";
    return (0, dice_walk_js_1.d20sOfMessage)(msg.rolls).map((d) => base({
        id: `${msg._id}:r${d.rollIndex}:t${d.termIndex}:d${d.resultIndex}`,
        dieIndex: d.dieIndex,
        natural: d.natural,
        kept: d.kept,
        formula: d.formula,
        total: d.total,
        type,
        source: "raw",
    }));
}
},
"scripts/capture/extractors/toolbelt-saves.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.on = exports.id = void 0;
exports.matches = matches;
exports.extract = extract;
const dice_walk_js_1 = require("scripts/capture/dice-walk.js");
const sanitize_js_1 = require("scripts/capture/sanitize.js");
exports.id = "toolbelt-saves";
exports.on = ["create", "update", "backfill"];
const FLAG_SCOPE = "pf2e-toolbelt";
const MAX_TARGETS = 64;
const MAX_VARIANTS = 8;
const MAX_REROLLS = 4;
function matches(msg) {
    return listSaves(msg).length > 0;
}
function extract(msg, ctx, base) {
    const out = [];
    for (const { variantKey, variant, tokenId, sceneId, save } of listSaves(msg)) {
        const roll = (0, dice_walk_js_1.parseRoll)(save.roll);
        const options = roll?.options && typeof roll.options === "object" ? roll.options : {};
        const natural = numberOrNull(save.die ?? firstD20(roll));
        if (!(0, sanitize_js_1.isNatural)(natural))
            continue;
        const total = numberOrNull(save.value ?? roll?.total);
        const statistic = save.statistic ?? variant.statistic ?? null;
        const dc = numberOrNull(variant.dc);
        const token = ctx.resolveToken?.(sceneId, tokenId) ?? null;
        const rollerId = trustedRoller(options.rollerId, token);
        const userId = rollerId ?? (ctx.event === "update" ? ctx.updaterUserId ?? null : null);
        const baseId = `${msg._id}:tb:${safe(variantKey)}:${tokenId}`;
        const prev = ctx.existing?.(baseId);
        const prevSeq = prev ? seqOf(prev.id) : -1;
        const changed = prev && (prev.natural !== natural || prev.total !== total);
        if (changed && prevSeq >= MAX_REROLLS)
            continue;
        const seq = prev ? (changed ? prevSeq + 1 : prevSeq) : 0;
        out.push(base({
            id: `${baseId}:${seq}`,
            dieIndex: out.length,
            natural,
            kept: true,
            formula: typeof roll?.formula === "string" && /d20/.test(roll.formula) ? dieFormula(roll) : "1d20",
            total,
            type: "saving-throw",
            source: "toolbelt",
            domains: Array.isArray(options.domains) ? [...options.domains] : (statistic ? [statistic, "saving-throw"] : ["saving-throw"]),
            stat: statistic,
            ident: statistic,
            action: variant.basic ? "basic-save" : null,
            dc,
            dcVisible: dc !== null ? true : null,
            outcome: normalizeOutcome(save.success ?? save.outcome ?? options.degreeOfSuccess),
            unadjustedOutcome: normalizeOutcome(save.unadjustedOutcome) ?? null,
            isReroll: options.isReroll === true || seq > 0,
            ...(seq > 0 && prev ? { rerollOf: prev.id } : {}),
            mode: save.private ? "blindroll" : null,
            blind: save.private === true,
            actorId: token?.actorId ?? null,
            tokenId,
            alias: token?.alias ?? null,
            userId,
            ...(rollerId ? {} : { userGuess: true }),
        }));
    }
    return out;
}
function trustedRoller(rollerId, token) {
    if (!(0, sanitize_js_1.isDocumentId)(rollerId))
        return null;
    if (Array.isArray(token?.rollers) && !token.rollers.includes(rollerId))
        return null;
    return (rollerId);
}
function listSaves(msg) {
    const helper = msg?.flags?.[FLAG_SCOPE]?.targetHelper;
    if (!helper || typeof helper !== "object")
        return [];
    const sceneOf = new Map();
    for (const t of Array.isArray(helper.targets) ? helper.targets.slice(0, MAX_TARGETS) : []) {
        if (typeof t !== "string" || t.length > 80)
            continue;
        const m = /^Scene\.([A-Za-z0-9]{16})\.Token\.([A-Za-z0-9]{16})$/.exec(t);
        if (m)
            sceneOf.set(m[2], m[1]);
    }
    const out = [];
    const variants = helper.saveVariants && typeof helper.saveVariants === "object" ? helper.saveVariants : (helper.saves ? { null: { saves: helper.saves, dc: helper.dc, statistic: helper.statistic } } : {});
    for (const [variantKey, variant] of Object.entries(variants).slice(0, MAX_VARIANTS)) {
        const saves = variant?.saves && typeof variant.saves === "object" ? variant.saves : {};
        for (const [tokenId, save] of Object.entries(saves).slice(0, MAX_TARGETS)) {
            if (!(0, sanitize_js_1.isDocumentId)(tokenId) || !save || typeof save !== "object")
                continue;
            out.push({ variantKey, variant, tokenId, sceneId: sceneOf.get(tokenId) ?? null, save });
        }
    }
    return out;
}
function firstD20(roll) {
    const terms = Array.isArray(roll?.terms) ? roll.terms : [];
    for (const t of terms)
        if (Number(t?.faces) === 20 && Array.isArray(t.results) && t.results[0])
            return t.results[0].result;
    return null;
}
function dieFormula(roll) {
    const die = (roll.terms ?? []).find((t) => Number(t?.faces) === 20);
    if (!die)
        return "1d20";
    return `${die.number ?? 1}d20${Array.isArray(die.modifiers) ? die.modifiers.join("") : ""}`;
}
function normalizeOutcome(v) {
    if (typeof v === "string") {
        const s = v.replace(/[-_\s]/g, "").toLowerCase();
        if (s === "criticalsuccess")
            return "criticalSuccess";
        if (s === "criticalfailure")
            return "criticalFailure";
        if (s === "success" || s === "failure")
            return s;
    }
    if (typeof v === "number")
        return ["criticalFailure", "failure", "success", "criticalSuccess"][v] ?? null;
    return null;
}
function seqOf(id) {
    const n = Number(String(id).split(":").pop());
    return Number.isInteger(n) ? n : 0;
}
function safe(key) {
    return String(key).replace(/[^A-Za-z0-9_-]/g, "_");
}
function numberOrNull(v) {
    const n = Number(v);
    return v === null || v === undefined || Number.isNaN(n) ? null : n;
}
},
"scripts/capture/extractors/flat-check.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.on = exports.id = void 0;
exports.matches = matches;
exports.parseFlatCheckContent = parseFlatCheckContent;
exports.extract = extract;
const html_scan_js_1 = require("scripts/capture/html-scan.js");
exports.id = "flat-check";
exports.on = ["create", "backfill"];
const DC = /Flat Check DC is ?(?:<b>)? ?(\d{1,2})\b|\bDC ?(?:is)? ?:? ?(?:<b>)? ?(\d{1,2})\b/i;
const OUTCOME = /\bflat-check-(success|failure)\b/i;
function matches(msg) {
    const flags = msg?.flags;
    return !!flags && typeof flags === "object" && Object.prototype.hasOwnProperty.call(flags, "pf2-flat-check");
}
function parseFlatCheckContent(content) {
    if (typeof content !== "string")
        return { natural: null, dc: null, outcome: null };
    const html = (0, html_scan_js_1.prepareHtml)(content);
    const has = (e, ...names) => names.every((n) => e.classes.includes(n));
    const shown = (0, html_scan_js_1.numericElements)(html, ["h4"]).find((e) => has(e, "dice-total"))
        ?? (0, html_scan_js_1.numericElements)(html, ["span", "div"]).find((e) => has(e, "dice-total"))
        ?? (0, html_scan_js_1.numericElements)(html, ["li"]).find((e) => has(e, "die", "d20"));
    let natural = shown ? shown.value : null;
    if (natural !== null && (natural < 1 || natural > 20))
        natural = null;
    const dcm = DC.exec(html);
    const dc = dcm ? Number(dcm[1] ?? dcm[2]) : null;
    const om = OUTCOME.exec(html);
    const outcome = om ? om[1].toLowerCase() : null;
    return { natural, dc, outcome };
}
function extract(msg, ctx, base) {
    const { natural, dc, outcome } = parseFlatCheckContent(msg.content);
    return [base({
            id: `${msg._id}:flat:0`,
            dieIndex: 0,
            natural,
            kept: true,
            formula: "1d20",
            total: natural,
            type: "flat-check",
            source: "pf2-flat-check",
            domains: ["flat-check"],
            dc,
            dcVisible: dc !== null ? true : null,
            outcome,
            userGuess: true,
            ...(natural === null ? { valueHidden: true } : {}),
        })];
}
},
"scripts/sessions/bucket.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UNSCHEDULED = exports.DEFAULT_BOUNDARY_HOUR = exports.DEFAULT_TIMEZONE = void 0;
exports.isValidTimezone = isValidTimezone;
exports.wallClock = wallClock;
exports.sessionKeyFor = sessionKeyFor;
exports.dayWindow = dayWindow;
exports.localMidnight = localMidnight;
exports.localDateKey = localDateKey;
exports.isSessionKey = isSessionKey;
exports.parseKey = parseKey;
exports.sessionLabel = sessionLabel;
exports.compareKeys = compareKeys;
exports.DEFAULT_TIMEZONE = "America/Chicago";
exports.DEFAULT_BOUNDARY_HOUR = 6;
exports.UNSCHEDULED = "unscheduled";
const DAY_MS = 86_400_000;
const formatters = new Map();
function formatterFor(timezone) {
    let fmt = formatters.get(timezone);
    if (!fmt) {
        fmt = new Intl.DateTimeFormat("en-US", {
            timeZone: timezone,
            hourCycle: "h23",
            year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit",
        });
        formatters.set(timezone, fmt);
    }
    return fmt;
}
function isValidTimezone(timezone) {
    try {
        new Intl.DateTimeFormat("en-US", { timeZone: timezone });
        return true;
    }
    catch {
        return false;
    }
}
function wallClock(ts, timezone = exports.DEFAULT_TIMEZONE) {
    const out = { year: 0, month: 0, day: 0, hour: 0, minute: 0 };
    for (const part of formatterFor(timezone).formatToParts(ts)) {
        if (part.type in out)
            out[part.type] = Number(part.value);
    }
    if (out.hour === 24)
        out.hour = 0;
    return out;
}
function sessionKeyFor(ts, { timezone = exports.DEFAULT_TIMEZONE, boundaryHour = exports.DEFAULT_BOUNDARY_HOUR } = {}) {
    const w = wallClock(ts, timezone);
    let dayUtc = Date.UTC(w.year, w.month - 1, w.day);
    if (w.hour < boundaryHour)
        dayUtc -= DAY_MS;
    return isoDate(dayUtc);
}
function dayWindow(key) {
    const [y, m, d] = parseKey(key).base.split("-").map(Number);
    const day = Date.UTC(y, m - 1, d);
    return { lo: day - 1.5 * DAY_MS, hi: day + 2.5 * DAY_MS };
}
function localMidnight(dateKey, timezone = exports.DEFAULT_TIMEZONE) {
    const [y, m, d] = String(dateKey).split("-").map(Number);
    if (!y || !m || !d)
        return null;
    const noon = Date.UTC(y, m - 1, d, 12);
    const w = wallClock(noon, timezone);
    const offset = Date.UTC(w.year, w.month - 1, w.day, w.hour, w.minute) - noon;
    return Date.UTC(y, m - 1, d) - offset;
}
function localDateKey(ts, timezone = exports.DEFAULT_TIMEZONE) {
    return sessionKeyFor(ts, { timezone, boundaryHour: 0 });
}
const KEY = /^\d{4}-\d{2}-\d{2}(?:~\d{1,3})?$/;
function isSessionKey(key) {
    return key === exports.UNSCHEDULED || (typeof key === "string" && KEY.test(key));
}
function parseKey(key) {
    const [base, seq] = String(key).split("~");
    return { base, seq: seq ? Number(seq) : 1 };
}
function sessionLabel(key, locale = "en-US") {
    if (key === exports.UNSCHEDULED)
        return "Unscheduled";
    const { base, seq } = parseKey(key);
    const [y, m, d] = base.split("-").map(Number);
    if (!y || !m || !d)
        return String(key);
    const weekday = new Intl.DateTimeFormat(locale, { weekday: "short", timeZone: "UTC" }).format(Date.UTC(y, m - 1, d));
    return `${base} ${weekday}${seq > 1 ? ` (${seq})` : ""}`;
}
function compareKeys(a, b) {
    if (a === b)
        return 0;
    if (a === exports.UNSCHEDULED)
        return -1;
    if (b === exports.UNSCHEDULED)
        return 1;
    const pa = parseKey(a), pb = parseKey(b);
    if (pa.base !== pb.base)
        return pa.base < pb.base ? -1 : 1;
    return pa.seq - pb.seq;
}
function isoDate(utcMs) {
    return new Date(utcMs).toISOString().slice(0, 10);
}
},
"scripts/stats/luck.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_GUARDS = void 0;
exports.luckSummary = luckSummary;
exports.faceStats = faceStats;
exports.zBand = zBand;
const constants_js_1 = require("scripts/constants.js");
const normal_js_1 = require("scripts/stats/normal.js");
const binomial_js_1 = require("scripts/stats/binomial.js");
exports.DEFAULT_GUARDS = Object.freeze({ minN: 5, thinN: 15 });
function luckSummary(naturals, guards = exports.DEFAULT_GUARDS) {
    const xs = naturals.filter((v) => Number.isInteger(v) && v >= 1 && v <= 20);
    const n = xs.length;
    const minN = guards.minN ?? exports.DEFAULT_GUARDS.minN;
    const thinN = guards.thinN ?? exports.DEFAULT_GUARDS.thinN;
    if (n === 0) {
        return { n: 0, mean: null, delta: null, z: null, percentile: null, zGuard: "none", high: { count: 0, share: null, expected: 0.5 }, nat20: faceStats(0, 0), nat1: faceStats(0, 0) };
    }
    const mean = xs.reduce((s, v) => s + v, 0) / n;
    const delta = mean - constants_js_1.D20.mean;
    const z = delta / (constants_js_1.D20.sd / Math.sqrt(n));
    const zGuard = n < minN ? "none" : n < thinN ? "thin" : "ok";
    const highCount = xs.filter((v) => v >= 11).length;
    return {
        n, mean, delta, z, percentile: (0, normal_js_1.normalCdf)(z), zGuard,
        high: { count: highCount, share: highCount / n, expected: 0.5 },
        nat20: faceStats(n, xs.filter((v) => v === 20).length),
        nat1: faceStats(n, xs.filter((v) => v === 1).length),
    };
}
function faceStats(n, count) {
    const p = 1 / 20;
    return {
        count,
        expected: n * p,
        rate: n ? count / n : null,
        pAtLeast: n ? (0, binomial_js_1.binomialAtLeast)(n, count, p) : null,
        pAtMost: n ? (0, binomial_js_1.binomialAtMost)(n, count, p) : null,
    };
}
function zBand(z) {
    if (z === null || !Number.isFinite(z))
        return "none";
    const a = Math.abs(z);
    if (a < 1)
        return "noise";
    if (a < 2)
        return z > 0 ? "hot" : "cold";
    return z > 0 ? "blessed" : "cursed";
}
},
"scripts/stats/normal.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.erf = erf;
exports.normalCdf = normalCdf;
exports.twoSidedP = twoSidedP;
function erf(x) {
    if (x === 0)
        return 0;
    const sign = x < 0 ? -1 : 1;
    const ax = Math.abs(x);
    const t = 1 / (1 + 0.3275911 * ax);
    const poly = t * (0.254829592 + t * (-0.284496736 + t * (1.421413741 + t * (-1.453152027 + t * 1.061405429))));
    return sign * (1 - poly * Math.exp(-ax * ax));
}
function normalCdf(z) {
    if (!Number.isFinite(z))
        return z > 0 ? 1 : z < 0 ? 0 : NaN;
    return 0.5 * (1 + erf(z / Math.SQRT2));
}
function twoSidedP(z) {
    return 2 * (1 - normalCdf(Math.abs(z)));
}
},
"scripts/stats/binomial.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.logChoose = logChoose;
exports.binomialPmf = binomialPmf;
exports.binomialAtLeast = binomialAtLeast;
exports.binomialAtMost = binomialAtMost;
function logChoose(n, k) {
    if (k < 0 || k > n)
        return -Infinity;
    k = Math.min(k, n - k);
    let s = 0;
    for (let i = 1; i <= k; i++)
        s += Math.log(n - k + i) - Math.log(i);
    return s;
}
function binomialPmf(n, k, p) {
    if (k < 0 || k > n || n < 0)
        return 0;
    if (p <= 0)
        return k === 0 ? 1 : 0;
    if (p >= 1)
        return k === n ? 1 : 0;
    return Math.exp(logChoose(n, k) + k * Math.log(p) + (n - k) * Math.log(1 - p));
}
function binomialAtLeast(n, k, p) {
    if (k <= 0)
        return 1;
    if (k > n)
        return 0;
    if (p <= 0)
        return 0;
    if (p >= 1)
        return 1;
    if (k <= mode(n, p))
        return clamp(1 - sumOutwards(n, k - 1, p, -1));
    return clamp(sumOutwards(n, k, p, +1));
}
function binomialAtMost(n, k, p) {
    if (k < 0)
        return 0;
    if (k >= n)
        return 1;
    if (p <= 0)
        return 1;
    if (p >= 1)
        return 0;
    if (k >= mode(n, p))
        return clamp(1 - sumOutwards(n, k + 1, p, +1));
    return clamp(sumOutwards(n, k, p, -1));
}
function mode(n, p) {
    return Math.floor((n + 1) * p);
}
function sumOutwards(n, k, p, direction) {
    let term = binomialPmf(n, k, p);
    if (term === 0)
        return 0;
    const q = 1 - p;
    let s = term;
    if (direction > 0) {
        for (let i = k; i < n; i++) {
            term *= ((n - i) / (i + 1)) * (p / q);
            s += term;
            if (term < s * 1e-17)
                break;
        }
    }
    else {
        for (let i = k; i > 0; i--) {
            term *= (i / (n - i + 1)) * (q / p);
            s += term;
            if (term < s * 1e-17)
                break;
        }
    }
    return s;
}
function clamp(x) {
    return x < 0 ? 0 : x > 1 ? 1 : x;
}
},
"scripts/stats/basic.js": function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.histogram = histogram;
exports.missingFaces = missingFaces;
exports.extremeFaces = extremeFaces;
exports.describe = describe;
function histogram(naturals) {
    const h = new Array(20).fill(0);
    for (const v of naturals)
        if (Number.isInteger(v) && v >= 1 && v <= 20)
            h[v - 1]++;
    return h;
}
function missingFaces(hist) {
    const out = [];
    hist.forEach((c, i) => { if (c === 0)
        out.push(i + 1); });
    return out;
}
function extremeFaces(hist) {
    const max = Math.max(...hist);
    const min = Math.min(...hist);
    const most = [], least = [];
    hist.forEach((c, i) => { if (c === max)
        most.push(i + 1); if (c === min)
        least.push(i + 1); });
    return { most, mostCount: max, least, leastCount: min };
}
function describe(values) {
    const xs = values.filter((v) => Number.isFinite(v));
    const n = xs.length;
    if (n === 0)
        return { n: 0, sum: 0, mean: null, median: null, modes: [], min: null, max: null, sd: null };
    const sorted = [...xs].sort((a, b) => a - b);
    const sum = sorted.reduce((s, v) => s + v, 0);
    const mean = sum / n;
    const median = n % 2 ? sorted[(n - 1) / 2] : (sorted[n / 2 - 1] + sorted[n / 2]) / 2;
    const counts = new Map();
    for (const v of sorted)
        counts.set(v, (counts.get(v) ?? 0) + 1);
    const top = Math.max(...counts.values());
    const modes = [...counts.entries()].filter(([, c]) => c === top).map(([v]) => v);
    const sd = n > 1 ? Math.sqrt(sorted.reduce((s, v) => s + (v - mean) ** 2, 0) / (n - 1)) : null;
    return { n, sum, mean, median, modes, min: sorted[0], max: sorted[n - 1], sd };
}
}
};
const cache = {};
const load = (id) => {
  if (!Object.hasOwn(defs, id)) throw new Error("d20 analyzer: unknown module " + id);
  if (!cache[id]) { cache[id] = { exports: {} }; defs[id](load, cache[id], cache[id].exports); }
  return cache[id].exports;
};
load("scripts/analyze-entry.js");
})();
